<a href="https://colab.research.google.com/github/sudeshdhiwar60-jpg/Construction_cost_Analysis/blob/main/Netflix_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
df=pd.read_csv('/content/combinedNetflixData (1).txt',header=None,names=['CustID','Ratings'],usecols=[0,1])

In [4]:
df

           CustID  Ratings
0              1:      NaN
1         1488844      3.0
2          822109      5.0
3          885013      4.0
4           30878      4.0
...           ...      ...
24058258  2591364      2.0
24058259  1791000      2.0
24058260   512536      5.0
24058261   988963      3.0
24058262  1704416      3.0

[24058263 rows x 2 columns]

In [5]:
df.isnull().sum()

CustID        0
Ratings    4499
dtype: int64

In [6]:
movie_count = df.isnull().sum()
movie_count = movie_count['Ratings']
movie_count

4499

In [7]:
#To calculate how many unique user there
total_count=df['CustID'].nunique()
total_count

475257

In [8]:
customer_count=total_count-movie_count
customer_count

470758

In [9]:
# how much rating count there
rating_count=df['CustID'].count()-movie_count
rating_count

24053764

In [10]:
#Let's Just make a clear DataFrame

movie_id=None
movie_np=[]

#Iterate through CustID column
for i in df['CustID']:
  if ":" in i:
    #Udate the current movieid in column
    movie_id=int(i.replace(':',''))
  movie_np.append(movie_id)

In [11]:
movie_np

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 2,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 3,
 ...]

In [12]:
df['MovieID']=movie_np

In [13]:
df

           CustID  Ratings  MovieID
0              1:      NaN        1
1         1488844      3.0        1
2          822109      5.0        1
3          885013      4.0        1
4           30878      4.0        1
...           ...      ...      ...
24058258  2591364      2.0     4499
24058259  1791000      2.0     4499
24058260   512536      5.0     4499
24058261   988963      3.0     4499
24058262  1704416      3.0     4499

[24058263 rows x 3 columns]

In [14]:
df=df[df['Ratings'].notna()]

In [15]:
df

           CustID  Ratings  MovieID
1         1488844      3.0        1
2          822109      5.0        1
3          885013      4.0        1
4           30878      4.0        1
5          823519      3.0        1
...           ...      ...      ...
24058258  2591364      2.0     4499
24058259  1791000      2.0     4499
24058260   512536      5.0     4499
24058261   988963      3.0     4499
24058262  1704416      3.0     4499

[24053764 rows x 3 columns]

In [16]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   CustID   object
 1   Ratings  float64
 2   MovieID  int64
dtypes: float64(1), int64(1), object(1)
memory usage: 734.1+ MB

In [17]:
df['CustID']=df['CustID'].astype(int)
df

/tmp/ipykernel_46096/888980602.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['CustID']=df['CustID'].astype(int)

           CustID  Ratings  MovieID
1         1488844      3.0        1
2          822109      5.0        1
3          885013      4.0        1
4           30878      4.0        1
5          823519      3.0        1
...           ...      ...      ...
24058258  2591364      2.0     4499
24058259  1791000      2.0     4499
24058260   512536      5.0     4499
24058261   988963      3.0     4499
24058262  1704416      3.0     4499

[24053764 rows x 3 columns]

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 24053764 entries, 1 to 24058262
Data columns (total 3 columns):
 #   Column   Dtype
---  ------   -----
 0   CustID   int64
 1   Ratings  float64
 2   MovieID  int64
dtypes: float64(1), int64(2)
memory usage: 734.1 MB

In [19]:
#Pre-Filtering
#Remove all those users who has watched less movie
#Remove all those movies who has less ratings given by the people

In [20]:
df_movie_summary=df.groupby('MovieID')['Ratings'].agg(['count'])
df_movie_summary

         count
MovieID
1          547
2          145
3         2012
4          142
5         1140
...        ...
4495       614
4496      9519
4497       714
4498       269
4499       428

[4499 rows x 1 columns]

In [21]:
#Now we will create a Benchmark(consider a becnhmark value of 60 percentile)
movie_benchmark=round(df_movie_summary['count'].quantile(0.6),0)
movie_benchmark

908.0

In [22]:
#If any movie got number of ratings less than 908 people i will remove that movie

In [23]:
drop_movie_list=df_movie_summary[df_movie_summary['count']<movie_benchmark].index
drop_movie_list

Index([   1,    2,    4,    7,    9,   10,   11,   12,   13,   14,
       ...
       4480, 4481, 4486, 4487, 4491, 4494, 4495, 4497, 4498, 4499],
      dtype='int64', name='MovieID', length=2699)

In [24]:
df_customer_summary=df.groupby('CustID')['Ratings'].agg(['count'])
df_customer_summary

         count
CustID
6          153
7          195
8           21
10          49
25           4
...        ...
2649404     12
2649409     10
2649421      3
2649426     74
2649429     62

[470758 rows x 1 columns]

In [25]:
customer_benchmark=round(df_customer_summary['count'].quantile(0.6),0)
customer_benchmark

36.0

In [26]:
drop_customer_list=df_customer_summary[df_customer_summary['count']<customer_benchmark].index
drop_customer_list

Index([      8,      25,      33,      83,      94,     126,     130,     133,
           142,     149,
       ...
       2649337, 2649343, 2649351, 2649376, 2649379, 2649384, 2649401, 2649404,
       2649409, 2649421],
      dtype='int64', name='CustID', length=282042)

In [27]:
len(drop_customer_list)

282042

In [28]:
len(drop_movie_list)

2699

In [29]:
df=df[~df['CustID'].isin(drop_customer_list)]
df=df[~df['MovieID'].isin(drop_movie_list)]

In [30]:
df

           CustID  Ratings  MovieID
696        712664      5.0        3
697       1331154      4.0        3
698       2632461      3.0        3
699         44937      5.0        3
700        656399      4.0        3
...           ...      ...      ...
24056842  1055714      5.0     4496
24056843  2643029      4.0     4496
24056844   267802      4.0     4496
24056845  1559566      3.0     4496
24056846   293198      3.0     4496

[19695836 rows x 3 columns]

# Model Building

In [31]:
netflix_df=pd.read_csv('/content/NetflixMovieData (1).csv',header=None,names=['MovieID','Years','names'],usecols=[0,1,2])

In [32]:
netflix_df

       MovieID   Years                                              names
0            1  2003.0                                    Dinosaur Planet
1            2  2004.0                         Isle of Man TT 2004 Review
2            3  1997.0                                          Character
3            4  1994.0                       Paula Abdul's Get Up & Dance
4            5  2004.0                           The Rise and Fall of ECW
...        ...     ...                                                ...
17764    17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17765    17767  2004.0                  Fidel Castro: American Experience
17766    17768  2000.0                                              Epoch
17767    17769  2003.0                                        The Company
17768    17770  2003.0                                       Alien Hunter

[17769 rows x 3 columns]

surprice librari

In [33]:
!pip install scikit-surprise

Requirement already satisfied: scikit-surprise in /usr/local/lib/python3.12/dist-packages (1.1.4)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.5.3)
Requirement already satisfied: numpy>=1.19.5 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.26.4)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-surprise) (1.16.3)

In [34]:
!pip install numpy==1.26.4

Requirement already satisfied: numpy==1.26.4 in /usr/local/lib/python3.12/dist-packages (1.26.4)

In [35]:
from surprise import Reader,Dataset,SVD
from surprise.model_selection import cross_validate

In [36]:
reader=Reader()

In [42]:
data=Dataset.load_from_df(df[['CustID','MovieID','Ratings']][:100000],reader)

In [43]:
data

In [44]:
model=SVD()

In [45]:
cross_validate(model,data,measures=['RMSE'],cv=3)

{'test_rmse': array([1.02339094, 1.01755404, 1.0145147 ]),
 'fit_time': (0.8295209407806396, 0.8597793579101562, 0.871476411819458),
 'test_time': (0.11919093132019043, 0.3047983646392822, 0.3272132873535156)}

# recommendation

In [46]:
user_rating=df[df['CustID']==656399]
user_rating

          CustID  Ratings  MovieID
700       656399      4.0        3
313860    656399      3.0       83
531242    656399      2.0      156
577666    656399      4.0      175
938038    656399      4.0      206
...          ...      ...      ...
23809726  656399      2.0     4441
23831660  656399      2.0     4460
23951288  656399      4.0     4478
23953869  656399      3.0     4479
23985610  656399      3.0     4488

[64 rows x 3 columns]

In [47]:
user_656399=netflix_df.copy()

In [48]:
user_656399

       MovieID   Years                                              names
0            1  2003.0                                    Dinosaur Planet
1            2  2004.0                         Isle of Man TT 2004 Review
2            3  1997.0                                          Character
3            4  1994.0                       Paula Abdul's Get Up & Dance
4            5  2004.0                           The Rise and Fall of ECW
...        ...     ...                                                ...
17764    17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17765    17767  2004.0                  Fidel Castro: American Experience
17766    17768  2000.0                                              Epoch
17767    17769  2003.0                                        The Company
17768    17770  2003.0                                       Alien Hunter

[17769 rows x 3 columns]

In [49]:
user_656399=user_656399[~user_656399['MovieID'].isin(drop_movie_list)]

In [50]:
user_656399

       MovieID   Years                                              names
2            3  1997.0                                          Character
4            5  2004.0                           The Rise and Fall of ECW
5            6  1997.0                                               Sick
7            8  2004.0                         What the #$*! Do We Know!?
15          16  1996.0                                          Screamers
...        ...     ...                                                ...
17764    17766  2002.0  Where the Wild Things Are and Other Maurice Se...
17765    17767  2004.0                  Fidel Castro: American Experience
17766    17768  2000.0                                              Epoch
17767    17769  2003.0                                        The Company
17768    17770  2003.0                                       Alien Hunter

[15070 rows x 3 columns]

In [51]:
user_656399['Estimate_Rating']=user_656399['MovieID'].apply(lambda x:model.predict(656399,x).est )

/tmp/ipykernel_46096/3371556218.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  user_656399['Estimate_Rating']=user_656399['MovieID'].apply(lambda x:model.predict(656399,x).est )

In [52]:
user_656399

,MovieID,Years,names,Estimate_Rating
2,3,1997.0,Character,3.761994
4,5,2004.0,The Rise and Fall of ECW,3.982495
5,6,1997.0,Sick,3.614986
7,8,2004.0,What the #$*! Do We Know!?,3.611588
15,16,1996.0,Screamers,3.827412
...,...,...,...,...
17764,17766,2002.0,Where the Wild Things Are and Other Maurice Se...,3.603227
17765,17767,2004.0,Fidel Castro: American Experience,3.603227
17766,17768,2000.0,Epoch,3.603227
17767,17769,2003.0,The Company,3.603227
17768,17770,2003.0,Alien Hunter,3.603227

In [54]:
top_5=user_656399.sort_values('Estimate_Rating',ascending=False).head(5)

In [57]:
top_5

,MovieID,Years,names,Estimate_Rating
24,25,1997.0,Inspector Morse 31: Death Is Now My Neighbour,4.351478
17,18,1994.0,Immortal Beloved,4.067038
4,5,2004.0,The Rise and Fall of ECW,3.982495
15,16,1996.0,Screamers,3.827412
2,3,1997.0,Character,3.761994

In [56]:
from google.colab import sheets
sheet = sheets.InteractiveSheet(df=user_656399)

https://docs.google.com/spreadsheets/d/1M4T9LMUnviTtfJWrnpQfslDIW610tmvTyINVDD6CqF4/edit#gid=0